# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
cowsay "hi there!"
alias ppv='puppet parser validate"
alias cls='clear'
alias rm='rm -i'
